# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021ALS/TEST_J_2021ALS.srcs/sources_1/bd/test_ALS/ip/test_ALS_microblaze_0_0/test_ALS_microblaze_0_0.xci
# IP: The module: 'test_ALS_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021ALS/TEST_J_2021ALS.gen/sources_1/bd/test_ALS/ip/test_ALS_microblaze_0_0/test_ALS_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_ALS_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021ALS/TEST_J_2021ALS.gen/sources_1/bd/test_ALS/ip/test_ALS_microblaze_0_0/test_ALS_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_ALS_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021ALS/TEST_J_2021ALS.gen/sources_1/bd/test_ALS/ip/test_ALS_microblaze_0_0/test_ALS_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_ALS_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021ALS/TEST_J_2021ALS.srcs/sources_1/bd/test_ALS/ip/test_ALS_microblaze_0_0/test_ALS_microblaze_0_0.xci
# IP: The module: 'test_ALS_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021ALS/TEST_J_2021ALS.gen/sources_1/bd/test_ALS/ip/test_ALS_microblaze_0_0/test_ALS_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_ALS_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021ALS/TEST_J_2021ALS.gen/sources_1/bd/test_ALS/ip/test_ALS_microblaze_0_0/test_ALS_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_ALS_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021ALS/TEST_J_2021ALS.gen/sources_1/bd/test_ALS/ip/test_ALS_microblaze_0_0/test_ALS_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_ALS_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
