# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Kashif/Downloads/Nexys-A7-100T-Master.xdc

# Block Designs: bd/PMOD_IPs/PMOD_IPs.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs || ORIG_REF_NAME==PMOD_IPs} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_microblaze_0_2/PMOD_IPs_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_microblaze_0_2 || ORIG_REF_NAME==PMOD_IPs_microblaze_0_2} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_dlmb_v10_1/PMOD_IPs_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_dlmb_v10_1 || ORIG_REF_NAME==PMOD_IPs_dlmb_v10_1} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_ilmb_v10_1/PMOD_IPs_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_ilmb_v10_1 || ORIG_REF_NAME==PMOD_IPs_ilmb_v10_1} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_dlmb_bram_if_cntlr_1/PMOD_IPs_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==PMOD_IPs_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_ilmb_bram_if_cntlr_1/PMOD_IPs_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==PMOD_IPs_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_lmb_bram_1/PMOD_IPs_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_lmb_bram_1 || ORIG_REF_NAME==PMOD_IPs_lmb_bram_1} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_xbar_0/PMOD_IPs_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_xbar_0 || ORIG_REF_NAME==PMOD_IPs_xbar_0} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_microblaze_0_axi_periph_1/PMOD_IPs_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_microblaze_0_axi_periph_1 || ORIG_REF_NAME==PMOD_IPs_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_microblaze_0_axi_intc_0/PMOD_IPs_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_microblaze_0_axi_intc_0 || ORIG_REF_NAME==PMOD_IPs_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_microblaze_0_xlconcat_0/PMOD_IPs_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_microblaze_0_xlconcat_0 || ORIG_REF_NAME==PMOD_IPs_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_mdm_1_1/PMOD_IPs_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_mdm_1_1 || ORIG_REF_NAME==PMOD_IPs_mdm_1_1} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_clk_wiz_1_1/PMOD_IPs_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_clk_wiz_1_1 || ORIG_REF_NAME==PMOD_IPs_clk_wiz_1_1} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_rst_clk_wiz_1_100M_1/PMOD_IPs_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==PMOD_IPs_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_axi_gpio_0_3/PMOD_IPs_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_axi_gpio_0_3 || ORIG_REF_NAME==PMOD_IPs_axi_gpio_0_3} -quiet] -quiet

# IP: bd/PMOD_IPs/ip/PMOD_IPs_axi_gpio_1_2/PMOD_IPs_axi_gpio_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PMOD_IPs_axi_gpio_1_2 || ORIG_REF_NAME==PMOD_IPs_axi_gpio_1_2} -quiet] -quiet

# XDC: c:/Users/Kashif/Desktop/WS2024/EMP 2/LAB/PROJECT/Microblaze_and_other_IPs.gen/sources_1/bd/PMOD_IPs/PMOD_IPs_ooc.xdc
