# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Advanced_Hardware_Engineering/Nexys-A7-100T-Master.xdc

# Block Designs: D:/Advanced_Hardware_Engineering/Microblaze_task/Microblaze_task.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task || ORIG_REF_NAME==Microblaze_task} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_microblaze_0_0/Microblaze_task_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_microblaze_0_0 || ORIG_REF_NAME==Microblaze_task_microblaze_0_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_dlmb_v10_0/Microblaze_task_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_dlmb_v10_0 || ORIG_REF_NAME==Microblaze_task_dlmb_v10_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_ilmb_v10_0/Microblaze_task_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_ilmb_v10_0 || ORIG_REF_NAME==Microblaze_task_ilmb_v10_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_dlmb_bram_if_cntlr_0/Microblaze_task_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Microblaze_task_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_ilmb_bram_if_cntlr_0/Microblaze_task_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Microblaze_task_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_lmb_bram_0/Microblaze_task_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_lmb_bram_0 || ORIG_REF_NAME==Microblaze_task_lmb_bram_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_microblaze_0_axi_periph_imp_xbar_0/Microblaze_task_microblaze_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_microblaze_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==Microblaze_task_microblaze_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_microblaze_0_axi_periph_0/Microblaze_task_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Microblaze_task_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_microblaze_0_axi_intc_0/Microblaze_task_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Microblaze_task_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_microblaze_0_xlconcat_0/Microblaze_task_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Microblaze_task_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_mdm_1_0/Microblaze_task_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_mdm_1_0 || ORIG_REF_NAME==Microblaze_task_mdm_1_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_clk_wiz_1_0/Microblaze_task_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_clk_wiz_1_0 || ORIG_REF_NAME==Microblaze_task_clk_wiz_1_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_rst_clk_wiz_1_100M_0/Microblaze_task_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Microblaze_task_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: D:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_axi_uartlite_0_0/Microblaze_task_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Microblaze_task_axi_uartlite_0_0 || ORIG_REF_NAME==Microblaze_task_axi_uartlite_0_0} -quiet] -quiet

# XDC: D:/Advanced_Hardware_Engineering/Microblaze_task/Microblaze_task_ooc.xdc
