# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_microblaze_0_axi_periph_imp_xbar_0/Microblaze_task_microblaze_0_axi_periph_imp_xbar_0.xci
# IP: The module: 'Microblaze_task_microblaze_0_axi_periph_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_microblaze_0_axi_periph_imp_xbar_0/Microblaze_task_microblaze_0_axi_periph_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_task_microblaze_0_axi_periph_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_microblaze_0_axi_periph_imp_xbar_0/Microblaze_task_microblaze_0_axi_periph_imp_xbar_0.xci
# IP: The module: 'Microblaze_task_microblaze_0_axi_periph_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Advanced_Hardware_Engineering/Microblaze_task/ip/Microblaze_task_microblaze_0_axi_periph_imp_xbar_0/Microblaze_task_microblaze_0_axi_periph_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_task_microblaze_0_axi_periph_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
