# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/Advanced_Hardware_Engineering/Nexys-A7-100T-Master.xdc

# Block Designs: bd/test_ALS/test_ALS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS || ORIG_REF_NAME==test_ALS} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_microblaze_0_0/test_ALS_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_microblaze_0_0 || ORIG_REF_NAME==test_ALS_microblaze_0_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_dlmb_v10_0/test_ALS_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_dlmb_v10_0 || ORIG_REF_NAME==test_ALS_dlmb_v10_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_ilmb_v10_0/test_ALS_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_ilmb_v10_0 || ORIG_REF_NAME==test_ALS_ilmb_v10_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_dlmb_bram_if_cntlr_0/test_ALS_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==test_ALS_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_ilmb_bram_if_cntlr_0/test_ALS_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==test_ALS_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_lmb_bram_0/test_ALS_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_lmb_bram_0 || ORIG_REF_NAME==test_ALS_lmb_bram_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_xbar_0/test_ALS_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_xbar_0 || ORIG_REF_NAME==test_ALS_xbar_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_microblaze_0_axi_periph_0/test_ALS_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_microblaze_0_axi_periph_0 || ORIG_REF_NAME==test_ALS_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_microblaze_0_axi_intc_0/test_ALS_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_microblaze_0_axi_intc_0 || ORIG_REF_NAME==test_ALS_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_microblaze_0_xlconcat_0/test_ALS_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_microblaze_0_xlconcat_0 || ORIG_REF_NAME==test_ALS_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_mdm_1_0/test_ALS_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_mdm_1_0 || ORIG_REF_NAME==test_ALS_mdm_1_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_clk_wiz_1_0/test_ALS_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_clk_wiz_1_0 || ORIG_REF_NAME==test_ALS_clk_wiz_1_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_rst_clk_wiz_1_100M_0/test_ALS_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==test_ALS_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_axi_uartlite_0_0/test_ALS_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_axi_uartlite_0_0 || ORIG_REF_NAME==test_ALS_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/test_ALS/ip/test_ALS_PmodALS_0_0/test_ALS_PmodALS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ALS_PmodALS_0_0 || ORIG_REF_NAME==test_ALS_PmodALS_0_0} -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021ALS/TEST_J_2021ALS.gen/sources_1/bd/test_ALS/test_ALS_ooc.xdc
