#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XGPIO_NUM_INSTANCES 2

/* Definitions for peripheral AXI_GPIO_BUTTON */
#define XPAR_AXI_GPIO_BUTTON_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_AXI_GPIO_BUTTON_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_BUTTON_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_BUTTON_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_BUTTON_IS_DUAL 0x0
#define XPAR_AXI_GPIO_BUTTON_GPIO_WIDTH 0x5

/* Canonical definitions for peripheral AXI_GPIO_BUTTON */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_XGPIO_0_GPIO_WIDTH 0x5
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_LED */
#define XPAR_AXI_GPIO_LED_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_AXI_GPIO_LED_BASEADDR 0x40010000
#define XPAR_AXI_GPIO_LED_HIGHADDR 0x4001ffff
#define XPAR_AXI_GPIO_LED_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_LED_IS_DUAL 0x0
#define XPAR_AXI_GPIO_LED_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXI_GPIO_LED */
#define XPAR_XGPIO_1_BASEADDR 0x40010000
#define XPAR_XGPIO_1_HIGHADDR 0x4001ffff
#define XPAR_XGPIO_1_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_XGPIO_1_GPIO_WIDTH 0x10
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_MICROBLAZE_0_AXI_INTC_COMPATIBLE xlnx,axi-intc-4.1
#define XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR 0x3
#define XPAR_MICROBLAZE_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS 0x2
#define XPAR_MICROBLAZE_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_HANDLER_TABLE 0x0

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE xlnx,axi-intc-4.1
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x3
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x2
#define XPAR_XINTC_0_OPTIONS 0x0

/*  BOARD definition */
#define XPS_BOARD_NEXYS-A7-100T

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x20000
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_ADDR_SIZE 32

/* Device ID */
#define XPAR_DEVICE_ID "7a100t"

#endif  /* end of protection macro */