# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Board_pinout.xdc

# Block Designs: bd/tmp3_system/tmp3_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system || ORIG_REF_NAME==tmp3_system} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_microblaze_0_0/tmp3_system_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_microblaze_0_0 || ORIG_REF_NAME==tmp3_system_microblaze_0_0} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_dlmb_v10_0/tmp3_system_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_dlmb_v10_0 || ORIG_REF_NAME==tmp3_system_dlmb_v10_0} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_ilmb_v10_0/tmp3_system_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_ilmb_v10_0 || ORIG_REF_NAME==tmp3_system_ilmb_v10_0} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_dlmb_bram_if_cntlr_0/tmp3_system_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==tmp3_system_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_ilmb_bram_if_cntlr_0/tmp3_system_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==tmp3_system_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_lmb_bram_0/tmp3_system_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_lmb_bram_0 || ORIG_REF_NAME==tmp3_system_lmb_bram_0} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_mdm_1_0/tmp3_system_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_mdm_1_0 || ORIG_REF_NAME==tmp3_system_mdm_1_0} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_clk_wiz_1_0/tmp3_system_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_clk_wiz_1_0 || ORIG_REF_NAME==tmp3_system_clk_wiz_1_0} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_rst_clk_wiz_1_100M_0/tmp3_system_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==tmp3_system_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_axi_gpio_0_0/tmp3_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_axi_gpio_0_0 || ORIG_REF_NAME==tmp3_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_axi_uartlite_0_0/tmp3_system_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_axi_uartlite_0_0 || ORIG_REF_NAME==tmp3_system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/tmp3_system_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_smartconnect_0_0 || ORIG_REF_NAME==tmp3_system_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/bd_67c5.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_0/bd_67c5_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_1/bd_67c5_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_2/bd_67c5_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_3/bd_67c5_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_4/bd_67c5_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_5/bd_67c5_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_6/bd_67c5_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_7/bd_67c5_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_8/bd_67c5_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_9/bd_67c5_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_10/bd_67c5_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_11/bd_67c5_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_12/bd_67c5_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_13/bd_67c5_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_14/bd_67c5_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_15/bd_67c5_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_16/bd_67c5_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_17/bd_67c5_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_18/bd_67c5_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_19/bd_67c5_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_20/bd_67c5_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_21/bd_67c5_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_22/bd_67c5_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_23/bd_67c5_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_24/bd_67c5_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_25/bd_67c5_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_26/bd_67c5_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_27/bd_67c5_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_28/bd_67c5_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_29/bd_67c5_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_30/bd_67c5_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_31/bd_67c5_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_32/bd_67c5_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_33/bd_67c5_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_34/bd_67c5_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_35/bd_67c5_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_36/bd_67c5_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_37/bd_67c5_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_38/bd_67c5_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_39/bd_67c5_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/tmp3_system/ip/tmp3_system_util_vector_logic_0_0/tmp3_system_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp3_system_util_vector_logic_0_0 || ORIG_REF_NAME==tmp3_system_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_microblaze_0_0/tmp3_system_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp3_system_microblaze_0_0 || ORIG_REF_NAME==tmp3_system_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_microblaze_0_0/tmp3_system_microblaze_0_0_ooc_debug.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_dlmb_v10_0/tmp3_system_dlmb_v10_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_ilmb_v10_0/tmp3_system_ilmb_v10_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_dlmb_bram_if_cntlr_0/tmp3_system_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_ilmb_bram_if_cntlr_0/tmp3_system_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_lmb_bram_0/tmp3_system_lmb_bram_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_mdm_1_0/tmp3_system_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp3_system_mdm_1_0 || ORIG_REF_NAME==tmp3_system_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_mdm_1_0/tmp3_system_mdm_1_0_ooc_trace.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_clk_wiz_1_0/tmp3_system_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp3_system_clk_wiz_1_0 || ORIG_REF_NAME==tmp3_system_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_clk_wiz_1_0/tmp3_system_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp3_system_clk_wiz_1_0 || ORIG_REF_NAME==tmp3_system_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_clk_wiz_1_0/tmp3_system_clk_wiz_1_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_rst_clk_wiz_1_100M_0/tmp3_system_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp3_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==tmp3_system_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_axi_gpio_0_0/tmp3_system_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp3_system_axi_gpio_0_0 || ORIG_REF_NAME==tmp3_system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_axi_gpio_0_0/tmp3_system_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_axi_uartlite_0_0/tmp3_system_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp3_system_axi_uartlite_0_0 || ORIG_REF_NAME==tmp3_system_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_axi_uartlite_0_0/tmp3_system_axi_uartlite_0_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_1/bd_67c5_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_2/bd_67c5_arinsw_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_3/bd_67c5_rinsw_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_4/bd_67c5_awinsw_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_5/bd_67c5_winsw_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_6/bd_67c5_binsw_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_7/bd_67c5_aroutsw_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_8/bd_67c5_routsw_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_9/bd_67c5_awoutsw_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_10/bd_67c5_woutsw_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_11/bd_67c5_boutsw_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_12/bd_67c5_arni_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_13/bd_67c5_rni_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_14/bd_67c5_awni_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_15/bd_67c5_wni_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_16/bd_67c5_bni_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_20/bd_67c5_s00a2s_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_21/bd_67c5_sarn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_22/bd_67c5_srn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_23/bd_67c5_sawn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_24/bd_67c5_swn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_25/bd_67c5_sbn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_26/bd_67c5_m00s2a_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_27/bd_67c5_m00arn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_28/bd_67c5_m00rn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_29/bd_67c5_m00awn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_30/bd_67c5_m00wn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_31/bd_67c5_m00bn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_33/bd_67c5_m01s2a_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_34/bd_67c5_m01arn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_35/bd_67c5_m01rn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_36/bd_67c5_m01awn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_37/bd_67c5_m01wn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/bd_0/ip/ip_38/bd_67c5_m01bn_0_ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/ooc.xdc

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/ip/tmp3_system_smartconnect_0_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp3_system_smartconnect_0_0 || ORIG_REF_NAME==tmp3_system_smartconnect_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/User/Documents/GitHub/Hardware_vhdl_ip_files/tmp3_pmod_design_final/tmp3_pmod_design_final.gen/sources_1/bd/tmp3_system/tmp3_system_ooc.xdc
