# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_axi_intc_0/Block_OLEDRGB_microblaze_0_axi_intc_0.xci
# IP: The module: 'Block_OLEDRGB_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_axi_intc_0/Block_OLEDRGB_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_OLEDRGB_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_axi_intc_0/Block_OLEDRGB_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_OLEDRGB_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_axi_intc_0/Block_OLEDRGB_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_OLEDRGB_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_axi_intc_0/Block_OLEDRGB_microblaze_0_axi_intc_0.xci
# IP: The module: 'Block_OLEDRGB_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_axi_intc_0/Block_OLEDRGB_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_OLEDRGB_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_axi_intc_0/Block_OLEDRGB_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_OLEDRGB_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_axi_intc_0/Block_OLEDRGB_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_OLEDRGB_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
