# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/Block_OLEDRGB_PmodALS_0_0.xci
# IP: The module: 'Block_OLEDRGB_PmodALS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_pmod_bridge_0_0/PmodALS_pmod_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodALS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodALS_pmod_bridge_0_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodALS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodALS_axi_quad_spi_0_0} -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_pmod_bridge_0_0/PmodALS_pmod_bridge_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodALS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodALS_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/Block_OLEDRGB_PmodALS_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_OLEDRGB_PmodALS_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_OLEDRGB_PmodALS_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodALS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodALS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodALS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodALS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_ooc.xdc

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodALS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodALS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/Block_OLEDRGB_PmodALS_0_0.xci
# IP: The module: 'Block_OLEDRGB_PmodALS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_pmod_bridge_0_0/PmodALS_pmod_bridge_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodALS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodALS_pmod_bridge_0_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodALS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodALS_axi_quad_spi_0_0} -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_pmod_bridge_0_0/PmodALS_pmod_bridge_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodALS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodALS_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/Block_OLEDRGB_PmodALS_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_OLEDRGB_PmodALS_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_OLEDRGB_PmodALS_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodALS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodALS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodALS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodALS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_ooc.xdc

# XDC: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodALS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodALS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
