domain_path: C:\Users\User\Documents\GitHub\AHE_Group_G\Project_Work\Vitis_workspace\TMP3_J\export\TMP3_J\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
