# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Advanced_Hardware_Engineering/Nexys-A7-100T-Master.xdc

# Block Designs: bd/MicroblazeWithALS/MicroblazeWithALS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS || ORIG_REF_NAME==MicroblazeWithALS} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_microblaze_0_0/MicroblazeWithALS_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_microblaze_0_0 || ORIG_REF_NAME==MicroblazeWithALS_microblaze_0_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_dlmb_v10_0/MicroblazeWithALS_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_dlmb_v10_0 || ORIG_REF_NAME==MicroblazeWithALS_dlmb_v10_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_ilmb_v10_0/MicroblazeWithALS_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_ilmb_v10_0 || ORIG_REF_NAME==MicroblazeWithALS_ilmb_v10_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_dlmb_bram_if_cntlr_0/MicroblazeWithALS_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroblazeWithALS_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_ilmb_bram_if_cntlr_0/MicroblazeWithALS_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroblazeWithALS_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_lmb_bram_0/MicroblazeWithALS_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_lmb_bram_0 || ORIG_REF_NAME==MicroblazeWithALS_lmb_bram_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_microblaze_0_axi_periph_imp_xbar_0/MicroblazeWithALS_microblaze_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_microblaze_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==MicroblazeWithALS_microblaze_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_microblaze_0_axi_periph_0/MicroblazeWithALS_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MicroblazeWithALS_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_microblaze_0_axi_intc_0/MicroblazeWithALS_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_microblaze_0_axi_intc_0 || ORIG_REF_NAME==MicroblazeWithALS_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_microblaze_0_xlconcat_0/MicroblazeWithALS_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_microblaze_0_xlconcat_0 || ORIG_REF_NAME==MicroblazeWithALS_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_mdm_1_0/MicroblazeWithALS_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_mdm_1_0 || ORIG_REF_NAME==MicroblazeWithALS_mdm_1_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_clk_wiz_1_0/MicroblazeWithALS_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_clk_wiz_1_0 || ORIG_REF_NAME==MicroblazeWithALS_clk_wiz_1_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_rst_clk_wiz_1_100M_0/MicroblazeWithALS_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MicroblazeWithALS_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_axi_uartlite_0_0/MicroblazeWithALS_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_axi_uartlite_0_0 || ORIG_REF_NAME==MicroblazeWithALS_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MicroblazeWithALS/ip/MicroblazeWithALS_PmodOLEDrgb_0_0/MicroblazeWithALS_PmodOLEDrgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroblazeWithALS_PmodOLEDrgb_0_0 || ORIG_REF_NAME==MicroblazeWithALS_PmodOLEDrgb_0_0} -quiet] -quiet

# XDC: d:/Advanced_Hardware_Engineering/ALS_IP_Block/ALS_IP_Block.gen/sources_1/bd/MicroblazeWithALS/MicroblazeWithALS_ooc.xdc
