# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_full_adder_0_0/top_full_adder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_full_adder_0_0 || ORIG_REF_NAME==top_full_adder_0_0} -quiet] -quiet

# IP: bd/top/ip/top_full_adder_1_0/top_full_adder_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_full_adder_1_0 || ORIG_REF_NAME==top_full_adder_1_0} -quiet] -quiet

# IP: bd/top/ip/top_full_adder_2_0/top_full_adder_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_full_adder_2_0 || ORIG_REF_NAME==top_full_adder_2_0} -quiet] -quiet

# IP: bd/top/ip/top_full_adder_3_0/top_full_adder_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_full_adder_3_0 || ORIG_REF_NAME==top_full_adder_3_0} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_0_0/top_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_0_0 || ORIG_REF_NAME==top_xlslice_0_0} -quiet] -quiet

# IP: bd/top/ip/top_A_slice_0_0/top_A_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_A_slice_0_0 || ORIG_REF_NAME==top_A_slice_0_0} -quiet] -quiet

# IP: bd/top/ip/top_A_slice_1_0/top_A_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_A_slice_1_0 || ORIG_REF_NAME==top_A_slice_1_0} -quiet] -quiet

# IP: bd/top/ip/top_A_slice_2_0/top_A_slice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_A_slice_2_0 || ORIG_REF_NAME==top_A_slice_2_0} -quiet] -quiet

# IP: bd/top/ip/top_A_slice_1_1/top_A_slice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_A_slice_1_1 || ORIG_REF_NAME==top_A_slice_1_1} -quiet] -quiet

# IP: bd/top/ip/top_B_slice_0_0/top_B_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_B_slice_0_0 || ORIG_REF_NAME==top_B_slice_0_0} -quiet] -quiet

# IP: bd/top/ip/top_B_slice_1_0/top_B_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_B_slice_1_0 || ORIG_REF_NAME==top_B_slice_1_0} -quiet] -quiet

# IP: bd/top/ip/top_B_slice_2_0/top_B_slice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_B_slice_2_0 || ORIG_REF_NAME==top_B_slice_2_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconcat_0_0/top_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconcat_0_0 || ORIG_REF_NAME==top_xlconcat_0_0} -quiet] -quiet

# XDC: c:/Users/User/Documents/GitHub/AHE_Group_G/Lab_2/Exercise_1/Exercise_1.gen/sources_1/bd/top/top_ooc.xdc
