# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/Advanced_Hardware_Engineering/Nexys-A7-100T-Master.xdc

# Block Designs: F:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/Block_OLEDRGB.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB || ORIG_REF_NAME==Block_OLEDRGB} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_0/Block_OLEDRGB_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_microblaze_0_0 || ORIG_REF_NAME==Block_OLEDRGB_microblaze_0_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_dlmb_v10_0/Block_OLEDRGB_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_dlmb_v10_0 || ORIG_REF_NAME==Block_OLEDRGB_dlmb_v10_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_ilmb_v10_0/Block_OLEDRGB_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_ilmb_v10_0 || ORIG_REF_NAME==Block_OLEDRGB_ilmb_v10_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_dlmb_bram_if_cntlr_0/Block_OLEDRGB_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_OLEDRGB_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_ilmb_bram_if_cntlr_0/Block_OLEDRGB_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_OLEDRGB_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_lmb_bram_0/Block_OLEDRGB_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_lmb_bram_0 || ORIG_REF_NAME==Block_OLEDRGB_lmb_bram_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_xbar_0/Block_OLEDRGB_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_xbar_0 || ORIG_REF_NAME==Block_OLEDRGB_xbar_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_axi_periph_0/Block_OLEDRGB_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Block_OLEDRGB_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_axi_intc_0/Block_OLEDRGB_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Block_OLEDRGB_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_microblaze_0_xlconcat_0/Block_OLEDRGB_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Block_OLEDRGB_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_mdm_1_0/Block_OLEDRGB_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_mdm_1_0 || ORIG_REF_NAME==Block_OLEDRGB_mdm_1_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_clk_wiz_1_0/Block_OLEDRGB_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_clk_wiz_1_0 || ORIG_REF_NAME==Block_OLEDRGB_clk_wiz_1_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_rst_clk_wiz_1_100M_0/Block_OLEDRGB_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Block_OLEDRGB_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_axi_uartlite_0_0/Block_OLEDRGB_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_axi_uartlite_0_0 || ORIG_REF_NAME==Block_OLEDRGB_axi_uartlite_0_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodOLEDrgb_0_0/Block_OLEDRGB_PmodOLEDrgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_PmodOLEDrgb_0_0 || ORIG_REF_NAME==Block_OLEDRGB_PmodOLEDrgb_0_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodALS_0_0/Block_OLEDRGB_PmodALS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_PmodALS_0_0 || ORIG_REF_NAME==Block_OLEDRGB_PmodALS_0_0} -quiet] -quiet

# IP: f:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/ip/Block_OLEDRGB_PmodTMP3_0_0/Block_OLEDRGB_PmodTMP3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_OLEDRGB_PmodTMP3_0_0 || ORIG_REF_NAME==Block_OLEDRGB_PmodTMP3_0_0} -quiet] -quiet

# XDC: F:/Advanced_Hardware_Engineering/Vivado_2021/TEST_J_2021OLED/Block_OLEDRGB/Block_OLEDRGB_ooc.xdc
