# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Advanced_Hardware_Engineering/ALS_IP_Block/ALS_IP_Block.srcs/sources_1/bd/MicroblazeWithALS/ip/MicroblazeWithALS_ilmb_bram_if_cntlr_0/MicroblazeWithALS_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'MicroblazeWithALS_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Advanced_Hardware_Engineering/ALS_IP_Block/ALS_IP_Block.gen/sources_1/bd/MicroblazeWithALS/ip/MicroblazeWithALS_ilmb_bram_if_cntlr_0/MicroblazeWithALS_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroblazeWithALS_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Advanced_Hardware_Engineering/ALS_IP_Block/ALS_IP_Block.srcs/sources_1/bd/MicroblazeWithALS/ip/MicroblazeWithALS_ilmb_bram_if_cntlr_0/MicroblazeWithALS_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'MicroblazeWithALS_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Advanced_Hardware_Engineering/ALS_IP_Block/ALS_IP_Block.gen/sources_1/bd/MicroblazeWithALS/ip/MicroblazeWithALS_ilmb_bram_if_cntlr_0/MicroblazeWithALS_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroblazeWithALS_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
